### ISSUE TITLE
Downloading files way slower than usual

### ISSUE THREAD

**Issue by erturkdotgg** [distubejs/ytdl-core#1]
Its a ytdl issue. Fix is here: https://github.com/fent/node-ytdl-core/issues/1240

We need an update for distube fork to fix the issue.

**Comment by skick1234** [comment]
https://github.com/distubejs/ytdl-core/blob/1f25741e5428da2523681f8d50a0a752e845066c/lib/sig.js#L95-L107
I have a better solution in the source code already but I thought I won't have to use it.
Time to uncomment :>

**Comment by erturkdotgg** [comment]
> https://github.com/distubejs/ytdl-core/blob/1f25741e5428da2523681f8d50a0a752e845066c/lib/sig.js#L95-L107
> I have a better solution in the source code already but I thought I won't have to use it.
> Time to uncomment :>

Works perfect. Thank you very much.

**Comment by danitseitlin** [comment]
Did you experience `Error: read ECONNRESET` Error?
