### ISSUE TITLE
Access denied 403 by stream URL

### ISSUE THREAD

**Issue by 7thRA-ONE** [distubejs/ytdl-core#103]
Access denied 403 by stream URL

'https://rr5---sn-ab5l6nkd.googlevideo.com/videoplayback?expire=1725191039&ei=Hv_TZonGO5KFkucPx7KewAE&ip=44.223.47.160&id=o-AMw21GEC5VzTmCmTFAlcXHdTRjYIxDu7pwGZU0cifpZA&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=kx&mm=31%2C26&mn=sn-ab5l6nkd%2Csn-vgqsrnz7&ms=au%2Conr&mv=u&mvi=5&pl=24&siu=1&bui=AQmm2ezRUmm5h3q4T3epYcCHFDxUMJHDr5l1SzSEtgjCcOZLf8jkBMhSiZO6W1-X1obti6XXLA&spc=Mv1m9oCb72UiQqXP5ErIiocKxMTgifDUmdn1iEiXG64OO_Az5sQZlZywuPthqmNohdM9G17v6w&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=82UP5cqolTelLIeH-9A5h64Q&rqh=1&gir=yes&clen=4219375&dur=260.667&lmt=1699359457199736&mt=1725168772&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=4532434&n=bhqbrJIiVGz4MA&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=ABPmVW0wRQIhAPOc0-biJL6Kz_nkNZwhhlN0XmATZKhSff5br5vrUG-WAiAc8l2izpUD8AdUgZ-aXZtx5gRGZIhxXKkBI2PSC-4LZA%3D%3D&sig=AJfQdSswRQIgAZusVQnTLgqwqp3yD74ktFM4bEuGSSh5KC5qsze0R6QCIQD_6YsCLuadJDbiAtFOJEYLoWsWzi_JFyuR6Z69sxGr6A%3D%3D'

**Comment by davidgalarza** [comment]
Any update?

**Comment by VenomSA** [comment]
I can confirm I started getting this error again, everything was working fine lately, didn't changed a thing!
Anybody else?

**Comment by melenas1414** [comment]
the problem is with videos long, when we download the video youtube cut the transmission with error 403 when we have ~200MB

**Comment by Riders004** [comment]
> Access denied 403 by stream URL
> 
> 'https://rr5---sn-ab5l6nkd.googlevideo.com/videoplayback?expire=1725191039&ei=Hv_TZonGO5KFkucPx7KewAE&ip=44.223.47.160&id=o-AMw21GEC5VzTmCmTFAlcXHdTRjYIxDu7pwGZU0cifpZA&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=kx&mm=31%2C26&mn=sn-ab5l6nkd%2Csn-vgqsrnz7&ms=au%2Conr&mv=u&mvi=5&pl=24&siu=1&bui=AQmm2ezRUmm5h3q4T3epYcCHFDxUMJHDr5l1SzSEtgjCcOZLf8jkBMhSiZO6W1-X1obti6XXLA&spc=Mv1m9oCb72UiQqXP5ErIiocKxMTgifDUmdn1iEiXG64OO_Az5sQZlZywuPthqmNohdM9G17v6w&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=82UP5cqolTelLIeH-9A5h64Q&rqh=1&gir=yes&clen=4219375&dur=260.667&lmt=1699359457199736&mt=1725168772&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=4532434&n=bhqbrJIiVGz4MA&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=ABPmVW0wRQIhAPOc0-biJL6Kz_nkNZwhhlN0XmATZKhSff5br5vrUG-WAiAc8l2izpUD8AdUgZ-aXZtx5gRGZIhxXKkBI2PSC-4LZA%3D%3D&sig=AJfQdSswRQIgAZusVQnTLgqwqp3yD74ktFM4bEuGSSh5KC5qsze0R6QCIQD_6YsCLuadJDbiAtFOJEYLoWsWzi_JFyuR6Z69sxGr6A%3D%3D'

Ip kaha se mili teko

**Comment by tiago719** [comment]
Also having this error. Any updates on this?

**Comment by jaysun0** [comment]
If you get 403 error - changing ip may help. 
Or try to wait 3 or more days and 403 will go. 
That's what I do when my server start to get 403.

**Comment by hankthetank27** [comment]
@melenas1414 I am experiencing the same situation
