### ISSUE TITLE
"Error when parsing watch.html, maybe YouTube made a change."

### ISSUE THREAD

**Issue by BENx2115** [distubejs/ytdl-core#108]
## Describe the bug
Since yesterday I only get this error.
```
Error: Error when parsing watch.html, maybe YouTube made a change.
Please report this issue with the "1726751716488-watch.html" file on https://github.com/distubejs/ytdl-core/issues.
    at getWatchHTMLPage (/home/ben/downloader/node_modules/@distube/ytdl-core/lib/info.js:187:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async retryFunc (/home/ben/downloader/node_modules/@distube/ytdl-core/lib/info.js:121:16)
    at async exports.getBasicInfo (/home/ben/downloader/node_modules/@distube/ytdl-core/lib/info.js:44:16)
```

## Debug File
[1726751716488-watch.html](https://github.com/user-attachments/files/17060150/1726751716488-watch.html.txt)

## Environment

- @distube/ytdl-core version: `v4.14.4`
- Node.js version: `v20.17.0`
- Operating system: `Linux`

**Comment by KlasRoya** [comment]
this project and all projects based on similar approaches are dead. better move away from youtube scraping if this is all you rely on this approach .

**Comment by jaysun0** [comment]
> this project and all projects based on similar approaches are dead. better move away from youtube scraping if this is all you rely on this approach .

At the moment I don't know any alternatives (in js) to @distube. Do you?)

**Comment by hustLer2k** [comment]
> > this project and all projects based on similar approaches are dead. better move away from youtube scraping if this is all you rely on this approach .
> 
> At the moment I don't know any alternatives (in js) to distubejs/ytdl-core. Do you?)

you can set up your own instance of https://github.com/imputnet/cobalt (see info in their repo somewhere) or use their api or figure out what they do to avoid the ban

**Comment by ybd-project-ver1** [comment]
> > this project and all projects based on similar approaches are dead. better move away from youtube scraping if this is all you rely on this approach .
> 
> At the moment I don't know any alternatives (in js) to distubejs/ytdl-core. Do you?)

If you want to use the same ytdl-core (usage is different), I recommend https://github.com/ybd-project-ver1/ytdl-core. cobalt is a good option, but not suitable in this case.

**Comment by bunglegrind** [comment]
> > > this project and all projects based on similar approaches are dead. better move away from youtube scraping if this is all you rely on this approach .
> > 
> > 
> > At the moment I don't know any alternatives (in js) to distubejs/ytdl-core. Do you?)
> 
> you can set up your own instance of https://github.com/imputnet/cobalt (see info in their repo somewhere) or use their api or figure out what they do to avoid the ban

same issue there...

https://github.com/imputnet/cobalt/issues/647
