### ISSUE TITLE
1727350569578-base

### ISSUE THREAD

**Issue by solakcemalettin** [distubejs/ytdl-core#109]
[1727350569578-base.zip](https://github.com/user-attachments/files/17147715/1727350569578-base.zip)

**Comment by solakcemalettin** [comment]
my bot is working but not play a music

**Comment by solakcemalettin** [comment]
my bot is working but not playing a music

**Comment by ybd-project-ver1** [comment]
Sad to inform you, the current method used by @distube/ytdl-core is an old method, so you will need to edit your code a bit to eliminate this error.
And since this repository has not been updated for about a month, please use https://github.com/ybd-project-ver1/ytdl-core if you need a quick fix.
