### ISSUE TITLE
WARNING: Could not parse n transform function.  Please report this issue with the "1728610743569-base.js" file on https://github.com/distubejs/ytdl-core/issues.

### ISSUE THREAD

**Issue by ryukenshiroo** [distubejs/ytdl-core#110]
## Describe the bug

[1728610743569-base.zip](https://github.com/user-attachments/files/17336464/1728610743569-base.zip)

## Environment

- @distube/ytdl-core version: 4.14.4
- Node.js version: 21.7.3
- Operating system: Linux

**Comment by rafaelhovhannisyan24** [comment]
Same for me

**Comment by ryukenshiroo** [comment]
> Same for me

my friend has fixed it, look here
https://github.com/XM4ZE/ytdl-core

**Comment by rafaelhovhannisyan24** [comment]
Thanks worked for me!!!

**Comment by ryukenshiroo** [comment]
> Thanks worked for me!!!

okeyy

**Comment by andrei10k** [comment]
same for me. what is the fix?

**Comment by ryukenshiroo** [comment]
> same for me. what is the fix?

this
https://github.com/XM4ZE/ytdl-core/commit/83072a83aa6377313668900a89abe25d93b73d4b

**Comment by andrei10k** [comment]
but this is just a warning. for me the dld doesnt work any more. without any error. just times out. is this happening for you too ?

**Comment by Sothirich** [comment]
mine fixed by using 
`"dependencies": {
  "@distube/ytdl-core": "github:XM4ZE/ytdl-core"
}`

**Comment by andrei10k** [comment]
this works for me too. let's hope it will be fixed in the main repo also

**Comment by ryukenshiroo** [comment]
**If you find the same thing, then try doing this**

 change package.json from "@distube/ytdl-core": "^4.14.4" into "@distube/ytdl-core": "github:XM4ZE/ytdl-core"

**Comment by bunglegrind** [comment]
this is not a fix, - it's a workaround, sort of. you're actually removing this library in favor of your fork.

**Comment by ryukenshiroo** [comment]
yea, the important thing is that it can work rather than not at all

**Comment by andrei10k** [comment]
But we should keep the issue open. It is still a bug in this repo

**Comment by dionsyran2** [comment]
Hmm this seems a bit sketchy but it does work... I will probably change it back to distube's fork once it gets updated

**Comment by Judge-Paul** [comment]
The fix worked for me as well

**Comment by arcovoltaico** [comment]
I thought the last update of this repo would fix the issue, but it didn't for me. And the fix XM4ZE is no longer available!
Is there a way we can get it back? Cheers! @ryukenshiroo

**Comment by ryukenshiroo** [comment]
> Cheers
he just deleted it without giving any reason :)

**Comment by ybd-project-ver1** [comment]
Try this.
https://github.com/ybd-project-ver1/ytdl-core
