### ISSUE TITLE
Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by RoyLizhiyu** [distubejs/ytdl-core#112]
## Describe the bug
I'm building a Nextjs App. ytdl works on my local machine. But when it's deployed to Vercel or Netlify I got Sign in to confirm you’re not a bot Error. I've tried using Proxy and Cookies from my youtube account, both didn't work. Waiting for a solution.

## Debug File

![image](https://github.com/user-attachments/assets/673c0580-1b56-4cae-8698-f672188945a1)

## Environment

- @distube/ytdl-core version: @4.14.4
- Node.js version: @20.16
- Operating system:  Vercel/Netlify

**Comment by Jppblue** [comment]
Anybody fixed this? I'm having this exact error when launching to production, but not in Localhost:3000

**Comment by Abruccii** [comment]
Bump

Issue still persists.

It doesn't matter in which format the cookies are entered.
Used the Option 

```
const cookies = [
  { name: "cookie1", value: "COOKIE1_HERE" },
  { name: "cookie2", value: "COOKIE2_HERE" },
];
```

which is documented in Readme but logs tell me its old format

and also the option
```
const COOKIE = 'a=1; b=2';
stream = ytdl(video, {
                highWaterMark: 1 << 25,
                quality: 'highestaudio',
                requestOptions: {
                    headers: {
                      cookie: COOKIE
                    },
                  }
            }); 
```

**Comment by Maher-Zubair** [comment]
> Anybody fixed this? I'm having this exact error when launching to production, but not in Localhost:3000

same issue

**Comment by ybd-project-ver1** [comment]
Try this. (I fork @distube/ytdl-core to solve various problems. Also, usage is quite different from this one.)
https://github.com/ybd-project-ver1/ytdl-core

**Comment by RoyLizhiyu** [comment]
> Try this. (I fork @distube/ytdl-core to solve various problems. Also, usage is quite different from this one.) https://github.com/ybd-project-ver1/ytdl-core

I will try later! Thank you
