### ISSUE TITLE
[request for assistance with expert knowledge] browser build yields video URLs that return 403 status

### ISSUE THREAD

**Issue by warren-bank** [distubejs/ytdl-core#113]
* [repo](https://github.com/warren-bank/browser-ytdl-core/tree/distubejs/) w/ build scripts
* [tags](https://github.com/warren-bank/browser-ytdl-core/tags) that correspond to [npm releases](https://www.npmjs.com/package/@warren-bank/browser-ytdl-core?activeTab=versions), which only include the corresponding [_dist/_](https://github.com/warren-bank/browser-ytdl-core/tree/distubejs/dist/) directory
* [example userscript](https://github.com/warren-bank/browser-ytdl-core/blob/distubejs/example/es2020/ytdl-core.no-proxy.user.js) to test the current build
  - `@require` uses a relative path
* [issue](https://github.com/warren-bank/browser-ytdl-core/issues/1)
  - appears to be directly related to: [distubejs#31](https://github.com/distubejs/ytdl-core/issues/31)
  - starting a new issue to not pollute or hijack

Presumably, the messy part is how to replace [`undici`](https://github.com/nodejs/undici) with a `fetch` [wrapper](https://github.com/warren-bank/browser-ytdl-core/blob/distubejs/src/miniget/index.js). The [`agent`](https://github.com/distubejs/ytdl-core/blob/4.14.4/lib/agent.js) class is no-longer used, and we're relying on the browser to manage cookies. As is, all `fetch` requests get a _200_ response. And yet, no joy.. the videos return _403_.

If anyone wants a working browser-build to use in userscripts (etc), then I need some help to figure out what request/cookie is missing.. so the request for the video URLs is allowed.

**Comment by warren-bank** [comment]
__solved:__

OK, so lets file this under _serendipitous_.. [PR#111](https://github.com/distubejs/ytdl-core/pull/111/files) was opened yesterday, and it fixes the issue! _Please_ merge.

**Comment by bunglegrind** [comment]
you can take inspiration from:

https://addons.mozilla.org/en-US/firefox/addon/youtube_downloader_webx/

where https://github.com/fent/node-ytdl-core is actually used. 

However, I'm not sure this is the proper place for this discussion.

**Comment by hassanzohdy** [comment]
@warren-bank I know it is not relevant to the issue, but do you have any solution for auto generating cookies as they seem to be expired after certain time?
