### ISSUE TITLE
Could not parse n transform function. Please report this issue with the "1729887766611-base.js"

### ISSUE THREAD

**Issue by vitor-zanatta-walter** [distubejs/ytdl-core#116]
## Debug File
[1729887766611-base.txt](https://github.com/user-attachments/files/17527234/1729887766611-base.txt)

## Environment
- @distube/ytdl-core version: 4.14.4
- Node.js version: v20.12.1
- Operating system: Windows_NT 10.0.22631

**Comment by ybd-project-ver1** [comment]
Try this. https://github.com/ybd-project-ver1/ytdl-core
