### ISSUE TITLE
Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by Maher-Zubair** [distubejs/ytdl-core#117]
## Describe the bug
i am using @distube/ytdl-core for my project, but its returning error Sign in to confirm you’re not a bot. while i have added cookies but still same issue. but its working on my local machine.

## Debug File

![image](https://github.com/user-attachments/assets/8ce8866a-220f-47e5-b18d-c0cb46b61e21)

## Environment

- @distube/ytdl-core version: 4.14.4
- Node.js version: v21.7.3
- Operating system: Heroku/Render

**Comment by ybd-project-ver1** [comment]
Try this. (I fork @distube/ytdl-core to solve various problems. Also, usage is quite different from this one.)
https://github.com/ybd-project-ver1/ytdl-core
