### ISSUE TITLE
filterFormats Error

### ISSUE THREAD

**Issue by makotocolors** [distubejs/ytdl-core#118]
In the current implementation of the module, a bug has been identified within the filterFormats function. This bug results in the function returning an empty array when the filter is set to either "videoandaudio" or "audioandvideo." This issue was not present in earlier versions of the module; therefore, reverting to version 4.14.4 is necessary to restore the functionality of the format filtering feature. The regression in functionality affects users relying on these specific filter configurations.

- @distube/ytdl-core version: (latest) 4.15.0
- Node.js version: 22.1.0
- Operating system: Windows and Linux

**Comment by HugoLibanori** [comment]
same error here.

**Comment by Talgoo** [comment]
Same here,  I think its started at `4.15.0`

**Comment by skick1234** [comment]
Because youtube removed almost all formats that have both video and audio, you can use `ANDROID` or `WEB` client to get itag 18. (The default ones, `IOS` and `WEB_CREATOR`, don't have this format).
```js
ytdl.getInfo("...", {
  playerClients: ["IOS", "WEB_CREATOR", "ANDROID", "WEB"]
}).then(info => {
  const formats = ytdl.filterFormats(info.formats, "videoandaudio");
  console.log(formats);
});

**Comment by Talgoo** [comment]
I think the docs should be updated with this.

**Comment by makotocolors** [comment]
> Since YouTube has removed nearly all formats that include both video and audio, you can utilize the `ANDROID` or `WEB` client to access itag 18. The default clients, `IOS` and `WEB_CREATOR`, do not support this format. Consider using a combination of formats for enhanced quality.
> ```js
> ytdl.getInfo("...", {
>   playerClients: ["IOS", "WEB_CREATOR", "ANDROID", "WEB"]
> }).then(info => {
>   const formats = ytdl.filterFormats(info.formats, "videoandaudio");
>   console.log(formats);
> });
> ```

It worked, thx
