### ISSUE TITLE
Audio streaming isn'nt working now?

### ISSUE THREAD

**Issue by orewafuad** [distubejs/ytdl-core#119]
## Describe the bug

I have tried to make audio streaming, but I received a `miniget 403`, of course i'm using cookies

## Debug File

```
res.header("Content-Type", "audio/mpeg");
  ytdl(videoUrl, { filter: "audioonly", agent})
    .on("error", (err) => {
      console.error("Error:", err);
      res.status(500).send("Error streaming audio");
    })
    .pipe(res);
```

## Environment

- @distube/ytdl-core version: 4.15.1
- Node.js version: 16++
- Operating system: -

**Comment by datly** [comment]
same

**Comment by cupiditys** [comment]
+1

**Comment by eddyLazar** [comment]
I opened another issue but seems like it is related https://github.com/distubejs/ytdl-core/issues/127
