### ISSUE TITLE
Generated IP address not being used in outgoing undici request

### ISSUE THREAD

**Issue by mariusbegby** [distubejs/ytdl-core#12]
## Describe the bug
IP address from ipv6 rotation is not actually used in outgoing network request.

`undici` does not have `localAddress` on `request()` but instead on `Client`. You need to create a new `Client` and set localAddress there and then send request through `Client.request()`. Something like this:

```js
exports.request = async(url, options = {}) => {
  const { requestOptions } = options;

  const client = new Client('https://www.youtube.com', {
    localAddress: requestOptions.localAddress,
    autoSelectFamily: true
  });

  const req = await client.request({
    path: '/watch?v=rUxyKA_-grg', // example path
    method: 'GET',
  });

  //const req = await request(url, requestOptions);
  const code = req.statusCode.toString();
  if (code.startsWith('2')) {
    if (req.headers['content-type'].includes('application/json')) return req.body.json();
    return req.body.text();
  }
  if (code.startsWith('3')) return exports.request(req.headers.location, options);
  const e = new Error(`Status code: ${code}`);
  e.statusCode = req.statusCode;
  throw e;
};
```

The above snippet does not work, it throws some errors, so treat as pseudo code. But maybe it helps to understand that you need to initialize a new `Client` where `localAddress` is specified before sending the request. I unfortunately don't have any experience with `@distube/ytdl-core` codebase or `undici`, so don't know how to implement the fix.

Currently, `@distube/ytdl-core` versions using `undici` is not actually using the generated IP address, and thus the "IP rotation" has no effect.

## Environment

- @distube/ytdl-core version: 4.12.1
- Node.js version: v18.17.1
- Operating system: Win 11 Pro 22621.2215

**Comment by skick1234** [comment]
Available on `4.13.0`.
Guide: [IP Rotation](https://github.com/distubejs/ytdl-core#ip-rotation)
