### ISSUE TITLE
Error when trying to use download options

### ISSUE THREAD

**Issue by victorsouzaleal** [distubejs/ytdl-core#121]
## Describe the bug

After updating from version 4.14.4 to 4.15.1 I am having problems using download options causing this error below:
![image](https://github.com/user-attachments/assets/62143dec-5dd6-4fca-a1b2-ce83ae026e17)

## Code

```js
let videoStream = ytdl(id_video, {quality: "highest", filter:"videoandaudio", agent: yt_agent})
videoStream.pipe(fs.createWriteStream("video.mp4"))
videoStream.on("end", ()=>{
    let bufferVideo = fs.readFileSync(saidaVideo)
    fs.unlinkSync(saidaVideo)
    resolve(bufferVideo)
}).on('error', (err)=>{
    reject(err)
})
```

## Environment

- @distube/ytdl-core version: 4.15.1
- Node.js version: v23.1.0
- Operating system:  Arch Linux

**Comment by skick1234** [comment]
https://github.com/distubejs/ytdl-core/issues/118#issuecomment-2441791441
