### ISSUE TITLE
Do the highestaudio and highestvideo formats not work?

### ISSUE THREAD

**Issue by ryukenshiroo** [distubejs/ytdl-core#122]
## Describe the bug
I tried using highestaudio and highestvideo formats, but it didn't work, Likewise with audioonly and videoonly

## Environment

- @distube/ytdl-core version: 1.15.1
- Node.js version: 21
- Operating system: Linux

**Comment by ybd-project-ver1** [comment]
Try this.
https://github.com/ybd-project-ver1/ytdl-core

**Comment by ab42jj** [comment]
hello a i have qustion why the youtube not working with the bot?

**Comment by ryukenshiroo** [comment]
> Try this. https://github.com/ybd-project-ver1/ytdl-core

is there a ytdl create agent with cookies like distube?
```javascript
const ytdl = require("@distube/ytdl-core");
const agent = ytdl.createAgent([
  {
    domain: ".youtube.com",
    expirationDate: 1234567890,
    hostOnly: false,
    httpOnly: true,
    name: "---xxx---",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    value: "---xxx---",
  },
  {
    "...": "...",
  },
]);

**Comment by ybd-project-ver1** [comment]
Functions like the one that specifies a cookie (the `createAgent` function) are obsolete in @ybd-project/ytdl-core.
It basically works without cookies. If it does not work, you can use OriginalProxy (https://github.com/ybd-project-ver1/ytdl-core/tree/latest/examples/Default/OriginalProxy).

**Comment by ab42jj** [comment]
> Functions like the one that specifies a cookie (the `createAgent` function) are obsolete in @ybd-project/ytdl-core. It basically works without cookies. If it does not work, you can use OriginalProxy (https://github.com/ybd-project-ver1/ytdl-core/tree/latest/examples/Default/OriginalProxy).

if i write const ytdl = require('@ybd-project/ytdl-core'); it will work?

**Comment by ybd-project-ver1** [comment]
Usage differs from @distube/ytdl-core, a basic example is shown below.

```ts
import { YtdlCore } from '@ybd-project/ytdl-core';
// JS: const { YtdlCore } = require('@ybd-project/ytdl-core');

const ytdl = new YtdlCore();

ytdl.getBasicInfo();
ytdl.getFullInfo();
```

**Comment by ab42jj** [comment]
> ```ts
> YtdlCore 
> ```

[ WARNING ]: Specify poToken for stable and fast operation. See README for details.
[  INFO!  ]: Automatically generates poToken, but stable operation cannot be guaranteed.
[ WARNING ]: At least one client must be specified.
حدث خطأ أثناء جلب معلومات الفيديو: UnrecoverableError: All player APIs responded with an error. (Clients: web, mweb, tv, ios)
For details, specify `logDisplay: ["debug", "info", "success", "warning", "error"]` in the constructor options of the YtdlCore class.
Note: This error cannot continue processing. (Details: "Sign in to confirm you’re not a bot")
    at PlayerApi.getApiResponses (/home/container/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:913:174)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _getBasicInfo (/home/container/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:914:10600)
    at async getBasicInfo (/home/container/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:914:12792)
    at async fetchVideoInfo (/home/container/index.js:109:23) {
  playabilityStatus: 'Sign in to confirm you’re not a bot'
}

**Comment by ybd-project-ver1** [comment]
> [ WARNING ]: Specify poToken for stable and fast operation. See README for details. [ INFO! ]: Automatically generates poToken, but stable operation cannot be guaranteed. [ WARNING ]: At least one client must be specified. حدث خطأ أثناء جلب معلومات الفيديو: UnrecoverableError: All player APIs responded with an error. (Clients: web, mweb, tv, ios) For details, specify `logDisplay: ["debug", "info", "success", "warning", "error"]` in the constructor options of the YtdlCore class. Note: This error cannot continue processing. (Details: "Sign in to confirm you’re not a bot") at PlayerApi.getApiResponses (/home/container/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:913:174) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async _getBasicInfo (/home/container/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:914:10600) at async getBasicInfo (/home/container/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:914:12792) at async fetchVideoInfo (/home/container/index.js:109:23) { playabilityStatus: 'Sign in to confirm you’re not a bot' }

Most likely the IP is banned. In this case, we recommend using OriginalProxy.
In addition, where are you running YtdlCore?

**Comment by ab42jj** [comment]
> > [ WARNING ]: Specify poToken for stable and fast operation. See README for details. [ INFO! ]: Automatically generates poToken, but stable operation cannot be guaranteed. [ WARNING ]: At least one client must be specified. حدث خطأ أثناء جلب معلومات الفيديو: UnrecoverableError: All player APIs responded with an error. (Clients: web, mweb, tv, ios) For details, specify `logDisplay: ["debug", "info", "success", "warning", "error"]` in the constructor options of the YtdlCore class. Note: This error cannot continue processing. (Details: "Sign in to confirm you’re not a bot") at PlayerApi.getApiResponses (/home/container/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:913:174) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async _getBasicInfo (/home/container/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:914:10600) at async getBasicInfo (/home/container/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:914:12792) at async fetchVideoInfo (/home/container/index.js:109:23) { playabilityStatus: 'Sign in to confirm you’re not a bot' }
> 
> Most likely the IP is banned. In this case, we recommend using OriginalProxy. In addition, where are you running YtdlCore?

all still not working

**Comment by ab42jj** [comment]
> > [ WARNING ]: Specify poToken for stable and fast operation. See README for details. [ INFO! ]: Automatically generates poToken, but stable operation cannot be guaranteed. [ WARNING ]: At least one client must be specified. حدث خطأ أثناء جلب معلومات الفيديو: UnrecoverableError: All player APIs responded with an error. (Clients: web, mweb, tv, ios) For details, specify `logDisplay: ["debug", "info", "success", "warning", "error"]` in the constructor options of the YtdlCore class. Note: This error cannot continue processing. (Details: "Sign in to confirm you’re not a bot") at PlayerApi.getApiResponses (/home/container/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:913:174) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async _getBasicInfo (/home/container/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:914:10600) at async getBasicInfo (/home/container/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:914:12792) at async fetchVideoInfo (/home/container/index.js:109:23) { playabilityStatus: 'Sign in to confirm you’re not a bot' }
> 
> Most likely the IP is banned. In this case, we recommend using OriginalProxy. In addition, where are you running YtdlCore?

yes i was running YtdlCore

**Comment by evanfebrianto** [comment]
I encountered this issue as well

**Comment by richardsondx** [comment]
+1

**Comment by patterueldev** [comment]
I remained on 4.14.4 for now because the latest version is having this issue.
