### ISSUE TITLE
TypeScript compilation fails

### ISSUE THREAD

**Issue by dani-mp** [distubejs/ytdl-core#13]
## Describe the bug
`tsc --project .` fails because of the types of a third party lib.

```
node_modules/@distube/ytdl-core/typings/index.d.ts:3:43 - error TS7016: Could not find a declaration file for module 'tough-cookie'. '<project-root>/node_modules/tough-cookie/lib/cookie.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/tough-cookie` if it exists or add a new declaration (.d.ts) file containing `declare module 'tough-cookie';`

3   import { Cookie as CK, CookieJar } from 'tough-cookie';
```

## Environment

- @distube/ytdl-core version: 4.12.1
- Node.js version: v16.17.1
- Operating system: macOs Monterey (12.5)

**Comment by skick1234** [comment]
As the error said, you have to use  `npm i --save-dev @types/tough-cookie` (or `yarn add -D`, ... depends on your package manager) to install its declaration files.

This is not a production dependency so it won't be installed by default.

**Comment by dani-mp** [comment]
@skick1234 right, but as I'm not using that library myself, it doesn't make sense to include it in my list of dependencies. The library could do it instead. If this is not possible, maybe adding a note about it in https://github.com/distubejs/ytdl-core#installation would be good enough. But I think it's the library that should add this dependency.

**Comment by skick1234** [comment]
I get where you're coming from, but in the TypeScript world, it's kinda like a standard thing to have those type declarations for third-party stuff. It makes your codebase cleaner and helps TypeScript do its magic.

Still, I hear you! I'll think about making 'ytdl-core' handle this dependency or, at the very least, slap a note in the docs about it. Thanks for raising it, and if you've got more thoughts or run into any other quirks, just give me a shout. I'm here to make things easier for ya!
