### ISSUE TITLE
Error when parsing watch.html

### ISSUE THREAD

**Issue by RayhanZuck** [distubejs/ytdl-core#131]
Error when parsing watch.html, maybe YouTube made a change.
Please report this issue with the "1733739707190-watch.html" file on https://github.com/distubejs/ytdl-core/issues.

**Comment by maximejacquetauchan** [comment]
I have the same issue, when I do: `ytdl.chooseFormat` 
I get this error: `No such format found: hd720`(And I tried multiple video formats (large, hd720, highestvideo, etc))

**Comment by maxime1jacquet** [comment]
@RayhanZuck I had the same issue, and I think I had 3 different issues.

**First :** 
Make sur your package `@distubejs/ytdl-core` is up to date and use version 22 of node. 

**Then :**
After that, try to update the file `sig.js` inside `node_modules/@distube/ytdl-core/lib`. 

Thank to : [https://github.com/distubejs/ytdl-core/issues/134#issuecomment-2533208953](https://github.com/distubejs/ytdl-core/issues/134#issuecomment-2533208953)

**Finally :**
If like me you have configuration like this :
```js
const format = ytdl.chooseFormat(videoInfo.formats, {
    quality: 'highestvideo',
    filter: 'videoandaudio'
}
```
 
You can update your code like : 
```js
const format = ytdl.chooseFormat(videoInfo.formats, {});
```

The best available quality is automatically download.

**Comment by skick1234** [comment]
Need debug file for more information
