### ISSUE TITLE
no longer working from aws machine even with cookies

### ISSUE THREAD

**Issue by andrei10k** [distubejs/ytdl-core#132]
recently is stopped working from my aws nodejs server. it happened for 1-2 days i believe. from localhost it works just fine. i'm using cookies, i renewed the cookies and still not working. and im not getting any error. it just hangs. also tried with the last 2 versions, same result

**Comment by Bankai77** [comment]
> Same issue. When not using cookies i get
> 
> ```
> AudioPlayerError: Sign in to confirm you’re not a bot
>     at exports.playError (/home/enju-silence/baniki/node_modules/@distube/ytdl-core/lib/utils.js:168:12)
>     at exports.getBasicInfo (/home/enju-silence/baniki/node_modules/@distube/ytdl-core/lib/info.js:43:25)
>     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
> ```
> 
> When trying with cookies i get
> 
> ```
> AudioPlayerError: Status code: 403
>     at ClientRequest.<anonymous> (/home/enju-silence/baniki/node_modules/miniget/dist/index.js:206:27)
>     at Object.onceWrapper (node:events:633:26)
>     at ClientRequest.emit (node:events:518:28)
>     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:704:27)
>     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
>     at TLSSocket.socketOnData (node:_http_client:546:22)
>     at TLSSocket.emit (node:events:518:28)
>     at addChunk (node:internal/streams/readable:561:12)
>     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
>     at Readable.push (node:internal/streams/readable:392:5)
> ```
> 
> but it seems a login issue cause i'm still getting "LOGIN_REQUIRED" error though not throwing on it.
> 
> On a local machine the bot is running smoothly with or without cookie-agent, but i am having no luck trying to launch it on a cloud VM. When I am trying to access YouTube via browser, it asks me to login and works fine after; though aquired cookies do not help.

Then what to do now ?

**Comment by Bankai77** [comment]
will proxy work ?

**Comment by skick1234** [comment]
Decipher update should fix this issue. Reopen if it still happens on latest version.

**Comment by andrei10k** [comment]
not working. same issue

**Comment by talgo-peachvideo** [comment]
I have the same problem, since this one is closed, I opened a new issue on this: https://github.com/distubejs/ytdl-core/issues/149
