### ISSUE TITLE
Issue with your ydtl-core fork package

### ISSUE THREAD

**Issue by willmil11** [distubejs/ytdl-core#14]
**[READ MY WHOLE MESSAGE BEFORE ANSWERING PLS]**

Using this code with your package
```js
(async function(){
    var ytdl = require("ytdl-core");
    var ended = false;
    ytdl("videoidplaceholder", {
        "quality": "highestvideo"
    })
    .pipe(require("fs").createWriteStream("video.mp4"))
    .on("finish", function () {
        ended = true;
    });
    while (ended === false) {
        await new Promise(resolve => setTimeout(resolve, 100));
    }
})()
```
First i installed and used ytdl-core base package then one day it stoped working so i read this: https://github.com/fent/node-ytdl-core/issues/1261 which led me to a comment with as solution installing your package with 
```bash
npm i ytdl-core@npm:@distube/ytdl-core
```

This was supposed to overwrite the base package so i don't have to change my code and it did but now when i use my code it just downloads a 0 byte empty file.

**Comment by skick1234** [comment]
Listen to `progress` and `info` events to make sure your code runs correctly.
I run your code and it works normally. `"ytdl-core": "npm:@distube/ytdl-core@^4.13.2"`
```js
(async function(){
    var ytdl = require("ytdl-core");
    var ended = false;
    ytdl("videoidplaceholder", {
        "quality": "highestvideo"
    })
    .on("info", console.log) // Or sth
    .on("progress", console.log)
    .pipe(require("fs").createWriteStream("video.mp4"))
    .on("finish", function () {
        ended = true;
        console.log("Finished!")
    });
    while (ended === false) {
        await new Promise(resolve => setTimeout(resolve, 100));
    }
})()
```

**Comment by minjaes** [comment]
I am also running into this issue. I upgraded to this package from base package recently and I see that even when I am using the same youtube link, it sometimes downloads 0 byte empty file.

**Comment by skick1234** [comment]
> I am also running into this issue. I upgraded to this package from base package recently and I see that even when I am using the same youtube link, it sometimes downloads 0 byte empty file.

I don't test the built-in stream too much. But it doesn't happen on my side. I will roll back the stream system and see if it works.

**Comment by skick1234** [comment]
I rolled back the old stream system with https://github.com/distubejs/ytdl-core/commit/304a43a690cfd799f53165baf7e489555af1e164.
miniget has built-in retry system while undici doesn't. This may cause your issue. Try it with `@distube/ytdl-core@4.13.3`

**Comment by skick1234** [comment]
If this problem still exists, feel free to re-open this issue.
