### ISSUE TITLE
No such format found: 'highest'

### ISSUE THREAD

**Issue by akashhubgit** [distubejs/ytdl-core#148]
## Describe the bug and how to reproduce it

var stream = ytdl(url,{
        quality: 'highest',
        filter: 'videoandaudio'
        });

I also tried:
var stream = ytdl(url,{
        format: 'highest',
        filter: 'videoandaudio'
        });

format: 'lowest' was also tried. I use current versions (update via npm install distube@latest)

**Comment by skick1234** [comment]
It is due to `filter: 'videoandaudio'` https://github.com/distubejs/ytdl-core/issues/127#issuecomment-2538759156
