### ISSUE TITLE
UnrecoverableError Sign in to confirm age

### ISSUE THREAD

**Issue by dev-syn** [distubejs/ytdl-core#15]
## Describe the bug

I was wondering how am I supposed to fix this error when youtube requires me to sign in I did use the agent and provided the cookie that I think I need

This is where I download the song
```
videoStream = ytdl(song.url,{
                agent: agent,
                quality: "highestaudio"
            });
```

I'm using the cookie with LOGIN_INFO as it's name

## Debug File

```
S:\MyDev\_Projects\Discord\TheDirector\node_modules\@distube\ytdl-core\lib\info.js:92
    return new UnrecoverableError(playability.reason || (playability.messages && playability.messages[0]));
           ^
Error: Sign in to confirm your age
    at privateVideoError (S:\MyDev\_Projects\Discord\TheDirector\node_modules\@distube\ytdl-core\lib\info.js:92:12)
    at exports.getBasicInfo (S:\MyDev\_Projects\Discord\TheDirector\node_modules\@distube\ytdl-core\lib\info.js:54:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
## Environment

- @distube/ytdl-core version: ^4.13.3
- Node.js version: v18.17.0
- Operating system: Windows 11

**Comment by dev-syn** [comment]
I would also add maybe if my cookie expired but I just go the cookie yesterday so I'm not sure if they expire within a day but other then that I'm not aware on how I can fix this

**Comment by skick1234** [comment]
https://github.com/distubejs/ytdl-core#cookies-support
If you added them, your cookies might be expired. There are many reasons to make your cookies revoked (log out, multiple IPs, etc). Anyway, it is not what we can handle with this project. Just get your cookie again until it works.

**Comment by dev-syn** [comment]
> https://github.com/distubejs/ytdl-core#cookies-support If you added them, your cookies might be expired. There are many reasons to make your cookies revoked (log out, multiple IPs, etc). Anyway, it is not what we can handle with this project. Just get your cookie again until it works.

Ok, thank you will do that.

**Comment by dev-syn** [comment]
> https://github.com/distubejs/ytdl-core#cookies-support If you added them, your cookies might be expired. There are many reasons to make your cookies revoked (log out, multiple IPs, etc). Anyway, it is not what we can handle with this project. Just get your cookie again until it works.

I just confirmed by getting my cookie again and it is not expired my expiration timestamp is: "expirationDate": 1735199412.856763

Which is today at like 8 AM but for me I'm writing this at 3 AM

This is my testing song: https://www.youtube.com/watch?v=rxZSYuzavhY

It works on the account when I go on it manually but not through the bot could it be anything else?

**Comment by skick1234** [comment]
Please provide your full code related to agent and ytdl

**Comment by dev-syn** [comment]
> Please provide your full code related to agent and ytdl

```ts
async function playSong(guildPlayer: AudioPlayer,song: Song): Promise<void> {
    return new Promise<void>((resolve, reject) => {
        let videoStream: internal.Readable | null = null;
        try {
            Logger.info("Playing song with url: " + song.url);
            // Download the video
            videoStream = ytdl(song.url,{
                agent: agent,
                quality: "highestaudio"
            });
        } catch(err) { return reject(err); }

        if (!videoStream) return;

        processVideo(videoStream)
        .then((voiceData: Buffer) => {
            const resource: AudioResource = createAudioResource(Readable.from([voiceData]),{ inputType: StreamType.Opus });
            guildPlayer.play(resource)
            try {
                guildPlayer.play(resource);
                resolve();
            } catch(err) { return reject(err); }
        })
        .catch(err => reject(new Error("Failed to play song with error: " + typeof err === "string" ? err : err.message)));
    });
}
```

This is the getting of the cookie process

```ts
async function getYTCookie(): Promise<Cookie> {
    const content: string = await fs.readFile(path.join('_Data','yt-cookie.json'),'utf-8');
    const ytCookie: Cookie = JSON.parse(content);
    return ytCookie;
}

let agent: ytdl.Agent;
// Pass the yt cookie to the agent
getYTCookie()
.then((cookie: Cookie) => {
    agent = ytdl.createAgent([cookie]);
})
.catch(err => {
    Logger.warn(err,"Youtube cookie could not be fetched no cookie will be assigned.");
    agent = ytdl.createAgent();
});
```

**Comment by skick1234** [comment]
I guess your cookie file is a cookie array, so you have to use `ytdl.createAgent(cookie)` instead of `ytdl.createAgent([cookie])`.
You should use zod for validate unknown json in ts.

**Comment by dev-syn** [comment]
> I guess your cookie file is a cookie array, so you have to use `ytdl.createAgent(cookie)` instead of `ytdl.createAgent([cookie])`. You should use zod to validate unknown json in ts.

It's not I thought of that ahead of time

Here is my whole json file excluding the value

```json
{
    "domain": ".youtube.com",
    "expirationDate": 1735286838.909133,
    "hostOnly": false,
    "httpOnly": true,
    "name": "LOGIN_INFO",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "REDACTED",
    "id": 12
}
```

**Comment by dev-syn** [comment]
> I guess your cookie file is a cookie array, so you have to use `ytdl.createAgent(cookie)` instead of `ytdl.createAgent([cookie])`. You should use zod to validate unknown json in ts.

Have you tried reproducing this with the test song I sent because my bot will play any song that is not age restricted

**Comment by skick1234** [comment]
> Have you tried reproducing this with the test song I sent because my bot will play any song that is not age restricted

You don't need cookie to play other songs

**Comment by dev-syn** [comment]
> > Have you tried reproducing this with the test song I sent because my bot will play any song that is not age restricted
> 
> You don't need cookie to play other songs

Ok, but 

```ts
let agent: ytdl.Agent;
// Pass the yt cookie to the agent
getYTCookie()
.then((cookie: Cookie) => {
    agent = ytdl.createAgent([cookie]);
})
.catch(err => {
    Logger.warn(err,"Youtube cookie could not be fetched no cookie will be assigned.");
    agent = ytdl.createAgent();
});
```

Here I have it log if the cookie could not be grabbed so it should be inserted into the agent

**Comment by skick1234** [comment]
Just try it and see.
We use CookieJar from tough-cookie, maybe it consider your nested array is an empty cookie without throwing errors.

**Comment by dev-syn** [comment]
> Just try it and see. We use CookieJar from tough-cookie, maybe it consider your nested array is an empty cookie without throwing errors.

I don't have a nested array? My json file is an object alone not inside of an array

**Comment by skick1234** [comment]
> > Just try it and see. We use CookieJar from tough-cookie, maybe it consider your nested array is an empty cookie without throwing errors.
> 
> I don't have a nested array? My json file is an object alone not inside of an array

So you have to follow the guide in readme file and export all the cookies, not one cookie.

**Comment by dev-syn** [comment]
> > > Just try it and see. We use CookieJar from tough-cookie, maybe it consider your nested array is an empty cookie without throwing errors.
> > 
> > 
> > I don't have a nested array? My json file is an object alone not inside of an array
> 
> So you have to follow the guide in readme file and export all the cookies, not one cookie.

Ohh I'm sorry I assumed it was just the LOGIN_INFO cookie and the others were not required let me add all the other cookies my bad

**Comment by skick1234** [comment]
i misread your https://github.com/distubejs/ytdl-core/issues/15#issuecomment-1824176194, I think you said you have an array like that

**Comment by dev-syn** [comment]
> i misread your [#15 (comment)](https://github.com/distubejs/ytdl-core/issues/15#issuecomment-1824176194), I think you said you have an array like that

No I believe you have identified my problem I only had the one cookie and not the others so let me try adding them and seeing if I can play the song

**Comment by skick1234** [comment]
> No I believe you have identified my problem I only had the one cookie and not the others so let me try adding them and seeing if I can play the song

Indeed, you need to provide an array of cookies. That's why I suggested using the extension to easily fetch all cookies, including HttpOnly cookies. I'll update the README to provide clearer instructions.

**Comment by dev-syn** [comment]
> > No I believe you have identified my problem I only had the one cookie and not the others so let me try adding them and seeing if I can play the song
> 
> Indeed, you need to provide an array of cookies. That's why I suggested using the extension to easily fetch all cookies, including HttpOnly cookies. I'll update the README to provide clearer instructions.

Yeah the issue is resolved thank you.

**Comment by ldenoue** [comment]
@skick1234 and @dev-syn  is there a way to get age restricted videos without cookies? e.g. it looks like the original ytdl-core had a way to use the /embed url to do this https://github.com/MAMISHO/node-ytdl-core/commit/dacb700e4ffefdd4d5744ba7318282fd369deb03

(although it doesn't seem to be working at the moment, see https://github.com/fent/node-ytdl-core/issues/19

**Comment by skick1234** [comment]
> @skick1234 and @dev-syn  is there a way to get age restricted videos without cookies? e.g. it looks like the original ytdl-core had a way to use the /embed url to do this https://github.com/MAMISHO/node-ytdl-core/commit/dacb700e4ffefdd4d5744ba7318282fd369deb03
> 
> 
> 
> (although it doesn't seem to be working at the moment, see https://github.com/fent/node-ytdl-core/issues/19
> 
> 

Don't crosspost. Old embed method doesn't work and you still need cookies to prevent 429.

**Comment by ldenoue** [comment]
@skick1234 thank you. By crossposting you mean it's not allowed to post links to other repos that could inform a question I have here? Or is it just something you personally don't want to happen here?

**Comment by skick1234** [comment]
> @skick1234 thank you. By crossposting you mean it's not allowed to post links to other repos that could inform a question I have here? Or is it just something you personally don't want to happen here?

Actually, it is my fault since I didn't change the issue title. This issue is about his cookies cannot bypass the age gate. So it is not related to your question at all. Feel free to create a new issue for additional questions or feature requests.

**Comment by skick1234** [comment]
@ldenoue and as I said above, you still need cookies if you don't want to get rate limited (429). So I don't think it is necessary to implement another way to bypass age-restricted content. If you still need it, just create a feature request and I will investigate it in a nice day (or close as not planned 🤣)

**Comment by northamerican** [comment]
```
  const agent = ytdl.createAgent([
    {
      name: "__Secure-1PSID",
      secure: true,
      value:
        "REDACTED",
    },
    {
      name: "__Secure-1PSIDTS",
      secure: true,
      value:
        "REDACTED",
    },
    {
      name: "LOGIN_INFO",
      secure: true,
      value:
        "REDACTED",
    },
  ]);
```
if anyone's curious, these are the fewest cookies needed. the values from these three can be changed set manually if you prefer.
