### ISSUE TITLE
an error occurs when fetching a stream url

### ISSUE THREAD

**Issue by WolfTwi97** [distubejs/ytdl-core#19]
## Describe the bug
I get an error when trying to fetch a googlevideo.com stream url, I can give u my code if u want.

## Debug File
[](https://cdn.discordapp.com/attachments/1175925849946603550/1243422239806980107/debug.txt?ex=66516ab3&is=66501933&hm=815be6efbaf6fb896d394f6eec284e31cf540a12adbe02e591b4ed2443e05d83&)

## Environment

- @distube/ytdl-core version: latest
- Node.js version: 20.13.1
- Operating system: Windows 11 Home

**Comment by WolfTwi97** [comment]
https://cdn.discordapp.com/attachments/1175925849946603550/1243422239806980107/debug.txt?ex=66516ab3&is=66501933&hm=815be6efbaf6fb896d394f6eec284e31cf540a12adbe02e591b4ed2443e05d83&
heres the link

**Comment by skick1234** [comment]
This package is for `youtube.com`, not `googlevideo.com`
