### ISSUE TITLE
what i should do?

### ISSUE THREAD

**Issue by Hoshimikan6490** [distubejs/ytdl-core#2]
when I play music from youtube, I got an issue like this.
```
Could not parse n transform function, please report it on @distube/ytdl-core GitHub.
```

---
what i should do?

**Comment by Hoshimikan6490** [comment]
error message is only this one. So, I didn't know what to do.

**Comment by skick1234** [comment]
I forgot to put a debug file likes empty `player_response`.
But make sure you are using latest version of it `@distube@ytdl-core@4.11.12`

**Comment by Hoshimikan6490** [comment]
I restarted the BOT by running the `npm i` command with `"@distube/ytdl-core":"^4.11.12"` in `package.json`, but the same message appeared.

**Comment by onlinzc** [comment]
Could not parse n transform function, please report it on @distube/ytdl-core GitHub.

i got the same thing

**Comment by skick1234** [comment]
I released `4.11.13` version to create a debug file. You can install the latest version and send me the debug file for fixing it.

**Comment by Hoshimikan6490** [comment]
Thank you for your action.
I no longer get an error message, but there is no `watch.html` file anywhere in the project folder. Where is it generated?

**Comment by skick1234** [comment]
> Thank you for your action. I no longer get an error message, but there is no `watch.html` file anywhere in the project folder. Where is it generated?

The debug file is generated only when the warning is shown. And the file name will be in the warning.
