### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by 1982FenceHopper** [distubejs/ytdl-core#20]
## Describe the bug
Attempting to use ytdl.getInfo results in module not found error in Next.js 14.2.3

## Debug File
![image](https://github.com/distubejs/ytdl-core/assets/87438935/5116dc40-2f57-4bfb-b3cd-7f71046d790f)

## Environment
- @distube/ytdl-core version: 4.13.3
- Node.js version: 20.13.1
- Operating system: Linux (Windows WSL)

**Comment by skick1234** [comment]
Because this fork is dedicated to use with skick1234/DisTube, I added some update only for node.js server, not web client.
I will check and remove them in the next update.

**Comment by skick1234** [comment]
Because this fork is dedicated to use with https://github.com/skick1234/DisTube, I added some update only for node.js server, not web client.
I will check and remove them in the next update.

**Comment by 1982FenceHopper** [comment]
CLOSING: Fixed by running in server side API call. However, another issue has occured which is also prevalent in the core library, recommend you check this out @skick1234 

https://github.com/fent/node-ytdl-core/issues/1290
