### ISSUE TITLE
1720544746781-base.js

### ISSUE THREAD

**Issue by mamdouhaass** [distubejs/ytdl-core#23]
WARNING: @distube/ytsr is out of date! Update with "npm install @distube/ytsr@latest".
WARNING: Could not parse n transform function.
Please report this issue with the "1720544746781-base.js" file on https://github.com/distubejs/ytdl-core/issues.

**Comment by zDqrK404** [comment]
+1

**Comment by Englard** [comment]
+1

**Comment by skick1234** [comment]
Duplicated of #22
