### ISSUE TITLE
Could not parse n transform function

### ISSUE THREAD

**Issue by IamShubhamRajput** [distubejs/ytdl-core#24]
## Describe the bug
Could not parse n transform function

## Debug File
[1720546121963-base.zip](https://github.com/user-attachments/files/16147268/1720546121963-base.zip)

## Environment

- @distube/ytdl-core version: 4.13.4
- Node.js version: v22.2.0
- Operating system: Ubuntu 24.04 LTS

**Comment by zDqrK404** [comment]
+1

**Comment by TheGauntt** [comment]
I think this is the relevant file - https://github.com/distubejs/ytdl-core/blob/a92a9f06e8e0ee459bbc7c18021da70aec3b2255/lib/sig.js#L184 (line 184)

Possibly a regex change needed

**Comment by mamdouhaass** [comment]
@TheGauntt so should i just delete it from my code?

**Comment by TheGauntt** [comment]
No, take a look at this thread for a possible short-term fix: https://github.com/distubejs/ytdl-core/issues/22#issuecomment-2218681378

**Comment by skick1234** [comment]
Duplicated of #22
