### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ALi-ELoL** [distubejs/ytdl-core#25]
function.
Please report this issue with the "1720550123535-base.js" file on https://github.com/distubejs/ytdl-core/issues.
Stream URL may be slow but still works.

**Comment by avallois** [comment]
Same

**Comment by Seukoooowwdd** [comment]
Please report this issue with the "1720555069641-base.js" file on https://github.com/distubejs/ytdl-core/issues.
Stream URL may be slow but still works.

**Comment by Wojtoteka** [comment]
Could not parse n transform function.
Please report this issue with the "1720555934227-base.js" file on https://github.com/distubejs/ytdl-core/issues.
Stream URL may be slow but still works.

**Comment by BiancaaCiobanuu** [comment]
WARNING: Could not parse n transform function.
Please report this issue with the "1720556759792-base.js" file on https://github.com/distubejs/ytdl-core/issues.
Stream URL may be slow but still works.
DisTubeError [FFMPEG_EXITED]: ffmpeg exited with code 1
    at ChildProcess.<anonymous> (/home/container/node_modules/distube/dist/index.js:1170:26)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12) {
  errorCode: 'FFMPEG_EXITED'
}
[1720556759792-base.js.txt](https://github.com/user-attachments/files/16150229/1720556759792-base.js.txt)

**Comment by TheGauntt** [comment]
There's a workaround on this thread: https://github.com/distubejs/ytdl-core/issues/22

**Comment by Englard** [comment]
WARNING: Could not parse n transform function.
Please report this issue with the "1720557490951-base.js" file on https://github.com/distubejs/ytdl-core/issues.
Stream URL may be slow but still works.

**Comment by Seukoooowwdd** [comment]
WARNING: Could not parse n transform function.
Please report this issue with the "1720558642491-base.js" file on https://github.com/distubejs/ytdl-core/issues.
Stream URL may be slow but still works.

**Comment by Seukoooowwdd** [comment]
WARNING: Could not parse n transform function.
Please report this issue with the "1720558793504-base.js" file on https://github.com/distubejs/ytdl-core/issues.
Stream URL may be slow but still works.

**Comment by skick1234** [comment]
Duplicated of #22
