### ISSUE TITLE
Bug: WARNING: Could not parse n transform function.

### ISSUE THREAD

**Issue by RuzitoTV** [distubejs/ytdl-core#26]
## Describe the bug
Dear users, hoping you are well, I come to the aid of this error that I have in my Discord Bot V14 project with Distube, which when I want to run Distube, the following error appears.

![image](https://github.com/distubejs/ytdl-core/assets/150984937/205b4b5c-2373-404c-b7a3-8879d9fc399e)

## Debug File
[1720559378400-base.txt](https://github.com/user-attachments/files/16150672/1720559378400-base.txt)

## Environment

- @distube/ytdl-core version: ^4.13.4
- Node.js version: v18.20.3
- Operating system: Windows 11

**Comment by jtpotato** [comment]
Looks like #22

**Comment by skick1234** [comment]
Duplicated of #22
