### ISSUE TITLE
Version 4.13.4 introduces major breaking changes

### ISSUE THREAD

**Issue by nukeop** [distubejs/ytdl-core#30]
## Describe the bug
Specifically, the upgrade of some dependencies here: https://github.com/distubejs/ytdl-core/commit/efa92e91bdc18fd50897d0cb35ed96f4c86cc858

One upgrade that caused uncompilable code for me was undici 5->6, as detailed by somebody else here: https://github.com/nodejs/undici/discussions/3010

In general, as this commit upgrades major versions of the dependencies, it should cause a major version bump in the next release.

## Debug File

N/A

## Environment

- @distube/ytdl-core version: 4.13.4
- Node.js version: 20
- Operating system: All

**Comment by skick1234** [comment]
This is a fork so I don't care about semver, it is why there are many breaking changes while the version is still 4.x. 
Anyway, you can use overrides to downgrade your undici version.
I will replace this with a brand new project soon.

**Comment by nukeop** [comment]
I would but...  apparently overrides doesn't work with a monorepo if you're using npm workspaces. That's why I've been unsuccessfully trying to move to yarn or pnpm for the past few days.

**Comment by nukeop** [comment]
For anyone reading this in the future, I simply copied the code from this repo directly into my project (with the license and its notice), and installed the dependencies manually. I had to adapt the code a little bit but it works.
