### ISSUE TITLE
Could not parse n transform function

### ISSUE THREAD

**Issue by LioYunCho** [distubejs/ytdl-core#36]
## Describe the bug
Need help, how to fix this code, why always (Could not parse n transform function)
[1721095860683-base.txt](https://github.com/user-attachments/files/16242355/1721095860683-base.txt)

## Debug File
for debug file open via this link: https://codefile.io/f/XmO5LaGkRx
![Screenshot_63](https://github.com/user-attachments/assets/6f2dce63-6338-4e70-b9fe-4e1072420e75)

## Environment

- @distube/ytdl-core version: 4.11.8
- Node.js version: 20
- Operating system: All

**Comment by skick1234** [comment]
It is very oudated version.

**Comment by LioYunCho** [comment]
> It is very oudated version.

then how should I update to a newer version?

**Comment by skick1234** [comment]
Ofc, depends on how you install it 🫥

**Comment by LioYunCho** [comment]
> Ofc, depends on how you install it 🫥

Thank you very much, now it's running normally
