### ISSUE TITLE
1721563732748-base.js

### ISSUE THREAD

**Issue by h4ppyfox78** [distubejs/ytdl-core#40]
## Describe the bug
Please report this issue with the "1721563732748-base.js" file on https://github.com/distubejs/ytdl-core/issues.

## Debug File
[1721563490715-base.txt](https://github.com/user-attachments/files/16324373/1721563490715-base.txt)

## Environment

- @distube/ytdl-core version:
- Node.js version:
- Operating system:

**Comment by Hoshimikan6490** [comment]
Please update @distube/ytdl-core to ver. 4.13.5 using `npm install @distube/ytdl-core@latest` command.

**Comment by h4ppyfox78** [comment]
i will do it

**Comment by skick1234** [comment]
Duplicated #22
