### ISSUE TITLE
How can I set quality for dowloading a private video with cookie?

### ISSUE THREAD

**Issue by nnhjs** [distubejs/ytdl-core#41]
## Describe the bug
- I can download a private video with cookie but I cannot set quality for this video. When I set quality so download an zero by video. 

## Environment
- @distube/ytdl-core version: 4.13.5
- Node.js version: 22.1.0
- Operating system: MacOS

## My code
```
const cookies = [ ];
const ytdl = require("@distube/ytdl-core");
const agent = ytdl.createAgent(cookies);

const videoID = '';

ytdl(`http://www.youtube.com/watch?v=${videoID}`, { agent, quality: 'highestvideo' })
.pipe(require("fs")
.createWriteStream("video3.mp4"));
```

**Comment by nnhjs** [comment]
After investigate, I see. We can download video with quality is `medium` - that quality is equal "360p".

**Comment by nnhjs** [comment]
After investigate, I see: 
- With 360 `hasVideo: true` and `hasAudio: true`
- Other quality with `hasVideo: true` and `hasAudio: false`
Maybe, this is a root cause.

**Comment by nnhjs** [comment]
I try to download `videoonly` but it doesn't work.

**Comment by vukgogo** [comment]
Stupid question, but when getting the cookies do we only set the LOGIN_INFO cookie object for the createAgent or do we also include the other ones as well such as YSC, PREF, etc...?

**Comment by nnhjs** [comment]
Oh, thannks for all reponses. I will try to the advices soon.

**Comment by nnhjs** [comment]
Maybe don't have anyone support this issue. I will close it!

**Comment by skick1234** [comment]
This is issues, for bug reporting, not a support service. If your issue still exists, you shouldn't close it.

If your problem is hq video doesn't have audio, this is how youtube encode their video. Duplicated of #34.

**Comment by nnhjs** [comment]
Thank you so much! I will try again when I have a time so I closed this PR. If anyone catch it who will report that. I think that so I close my issue.
