### ISSUE TITLE
Why is my code causing a 500 Internal Server Error on the server but running fine locally?

### ISSUE THREAD

**Issue by orewafuad** [distubejs/ytdl-core#43]
My code runs fine locally, but I'm getting a 500 Internal Server Error on the server. What could be the possible reasons for this?

`app.get('/audio', (req, res) => {
  const videoUrl = req.query.url; // Ambil URL video dari parameter query
  
  if (!videoUrl) {
    return res.status(400).send('Video URL is required');
  }

  res.header('Content-Type', 'audio/mpeg');
  ytdl(videoUrl, { filter: 'audioonly' })
    .on('error', (err) => {
      console.error('Error:', err);
      res.status(500).send('Error streaming audio');
    })
    .pipe(res);
});
`

**Comment by skick1234** [comment]
If you mean your server return 500, check the log since you `console.error` it
