### ISSUE TITLE
Getting 403 again

### ISSUE THREAD

**Issue by dhakan** [distubejs/ytdl-core#47]
## Describe the bug
Am getting 403 as of yesterday (?), perhaps the day before. Anyone else experienced this?

```ts
// Some code from my repo
  const info = await ytdl.getInfo(videoId);

  const format = ytdl.chooseFormat(info.formats, {
    quality: "lowestvideo",
  });

  const readableStream = ytdl.downloadFromInfo(info, { format });

// MinigetError: Status code: 403
```

This happens for every video that I've tried, maybe 20 so far.

## Environment

- @distube/ytdl-core version: 4.13.5
- Node.js version: 20
- Operating system: Alpine Linux

**Comment by ichsanulaulia** [comment]
Do you not use agents?

**Comment by dhakan** [comment]
> Do you not use agents?

I don't! Care to elaborate how that helps?

And do you think that helps this functionality from breaking?

**Comment by ichsanulaulia** [comment]
> > Do you not use agents?
> 
> I don't! Care to elaborate how that helps?
> 
> And do you think that helps this functionality from breaking?

readme.md

**Comment by skick1234** [comment]
Please upload your file, this bug should be fixed on latest version (4.13.5)

**Comment by skick1234** [comment]
403 mostly due to not using cookies, it is required due to youtube recent changes.
Anyway, duplicated of #31

**Comment by dhakan** [comment]
> > > Do you not use agents?
> > 
> > 
> > I don't! Care to elaborate how that helps?
> > And do you think that helps this functionality from breaking?
> 
> readme.md

To be fair, I've read the README several times, and it mentions proxies, cookies and agents, but not in which way that helps the project to not break. Maybe I'm missing something...

Also, did you just post this and followed up by reacting to your own post? That's funny 😍

In any case, I'll try to see what I can do with cookies and agents. Thanks.

**Comment by qubiack** [comment]
Exactly the same issue here. With agent and cookies credentials.

Error message I get:
```
Please report this issue with the "1722448515528-base.js" file on https://github.com/distubejs/ytdl-core/issues.

[Nest] 78967  - 07/31/2024, 7:55:15 PM   ERROR Error: Status code: 403
```

**Comment by dhakan** [comment]
@skick1234 I've started using a generated cookie (same one since a couple days back), and it worked for a while, but now it's broken 100% of the time it seems.

```ts
export async function downloadVideo(videoId: string, outputDir: string) {
  const agent = ytdl.createAgent([YT_LOGIN_INFO_COOKIE]);
  const info = await ytdl.getInfo(videoId, { agent });

  const format = ytdl.chooseFormat(info.formats, {
    quality: "lowestvideo",
  });

  const readableStream = ytdl.downloadFromInfo(info, { agent, format });

  const videoPath = path.join(outputDir, `video.${format.container}`);
  await fs.writeFile(videoPath, readableStream);
  return videoPath;
}
```

Is there anything else I can do to make this more robust? Because otherwise I'll probably nuke this part of my app. 

Disclaimer: I'm using the stream to generate thumbnails.

**Comment by websharik** [comment]
@dhakan Same problem. Using cookies/proxy is not resolve. most videos still 403.

@skick1234 Learn issue deeper. Full working example https://github.com/LuanRT/YouTube.js
