### ISSUE TITLE
1722337107854-base.js

### ISSUE THREAD

**Issue by ichsanulaulia** [distubejs/ytdl-core#48]
## Debug File
i got this error
WARNING: Could not parse n transform function.
The bug occurred when I searched for the audio and video paths separately like best audioonly  and best videoonly . before it worked. But this is the first time he has died 
## Environment

- @distube/ytdl-core version: Latest
- Node.js version: 20
- Operating system: linux

**Comment by Hoshimikan6490** [comment]
please check #22

**Comment by ichsanulaulia** [comment]
> please check #22

soya-daizu/ytdl-core#sig-patch gone 🥲

**Comment by skick1234** [comment]
Please upload your file, this bug should be fixed on latest version (4.13.5)

**Comment by ichsanulaulia** [comment]
> Please upload your file, this bug should be fixed on latest version (4.13.5)

file ? bug file or my code?


im using the latest version
and got this bug -_-

And what makes me wonder. I am only looking for video links and audio only. 
2 weeks ago since the new release it has not been a problem at all (till today) just got the bug

**Comment by ichsanulaulia** [comment]
![image](https://github.com/user-attachments/assets/8d227917-92cc-40df-9b44-6ccc5d19b7dc)
its work again ? 😂

**Comment by plasma119** [comment]
Got same error: WARNING: Could not parse n transform function.
Able to get audio/video format (not sure any error during this) but instant 403 miniget error on download on 3 videos

File:
[1722338287104-base.zip](https://github.com/user-attachments/files/16428909/1722338287104-base.zip)

Environment:
@distube/ytdl-core version: 4.13.5
Node.js version: 20.16.0
Operating system: Windows 10

**Comment by ichsanulaulia** [comment]
> Got same error: WARNING: Could not parse n transform function. Able to get audio/video format (not sure any error during this) but instant 403 miniget error on download on 3 videos
> 
> File: [1722338287104-base.zip](https://github.com/user-attachments/files/16428909/1722338287104-base.zip)
> 
> Environment: @distube/ytdl-core version: 4.13.5 Node.js version: 20.16.0 Operating system: Windows 10

![image](https://github.com/user-attachments/assets/7877e6c9-1e8e-437d-a501-2193cb58a551)
its totally work for me now 
idk why

**Comment by ichsanulaulia** [comment]
![image](https://github.com/user-attachments/assets/305e95b6-d59b-4d1f-b891-3be0f5d5bd90)
Some rrr links direct to other now, when clicked, he changes to rrr1 links
