### ISSUE TITLE
Please report this issue with the "1722450662874-base.js"

### ISSUE THREAD

**Issue by Seukoooowwdd** [distubejs/ytdl-core#50]
Please report this issue with the "1722450662874-base.js" file on https://github.com/distubejs/ytdl-core/issues.
Stream URL may be slow but still works.

**Comment by BowgartField** [comment]
same here

**Comment by Seukoooowwdd** [comment]
> pareil ici

Do you know how to fix the problem?

**Comment by BowgartField** [comment]
> > pareil ici
> 
> Do you know how to fix the problem?

Update to last version fixed for me

**Comment by Seukoooowwdd** [comment]
> > > pareil ici
> > 
> > 
> > Savez-vous comment résoudre le problème ?
> 
> Mise à jour vers la dernière version corrigée pour moi



> > > pareil ici
> > 
> > 
> > Savez-vous comment résoudre le problème ?
> 
> Mise à jour vers la dernière version corrigée pour moi

How did you do it?

**Comment by BowgartField** [comment]
yarn add @distube/ytdl-core

**Comment by Seukoooowwdd** [comment]
> yarn add @distube/ytdl-core

I didn't understand

**Comment by fmartinezjr** [comment]
> > yarn add @distube/ytdl-core
> 
> I didn't understand

It is fixed in `4.13.7`

**Comment by s875515** [comment]
> > > yarn add @distube/ytdl-core
> > 
> > 
> > I didn't understand
> 
> It is fixed in `4.13.7`

working well!

**Comment by omerman** [comment]
4.13.7 Fixes the issue 👍
