### ISSUE TITLE
Downloaded videos come with no sound

### ISSUE THREAD

**Issue by sssolammm** [distubejs/ytdl-core#53]
Describe the bug
When I download the following video is downloaded without sound, maybe codec is missing?

https://www.youtube.com/watch?v=kJQP7kiw5Fk

Debug File
No error msg have been displayed

Environment
@distube/ytdl-core version: 4.13.7
Node.js version: 20.12.1
Operating system: macOS_13.2.1

**Comment by qubiack** [comment]
This URL is working for me locally on `4.13.7`.  Could you share the `ytdl` code you try to use?

**Comment by skick1234** [comment]
You may downloaded an itag which has `hasAudio: false` property. You can use filter option or other to prevent it.

**Comment by sssolammm** [comment]
Hi,

Thanks for the answers I'm using this code to download the videos. There are several videos that I got issues and can't download them included the video that I said of no sound.

I will try to test ur solution for no sound, but the issues downloading oficial music videos it may be any problem in my code?
```

async function downloadVideo(youtubeUrl, outputFilePath) {
	return new Promise((resolve, reject) => {
		try {
			const outputStream = fs.createWriteStream(outputFilePath);

			outputStream.on('finish', () => {
				console.log('Download and writing to file completed.');
				resolve();
			});

			outputStream.on('error', (error) => {
				console.error('Error writing to file:', error);
				reject(error);
			});

			ytdl(youtubeUrl)
				.pipe(outputStream)
				.on('error', (error) => {
					console.error('Error downloading video:', error);
					reject(error);
				});
		} catch (error) {
			console.log('Error downloading video: ', error);
			reject(error);
		}
	});
}
```
