### ISSUE TITLE
Cannot download averagely videos that last more than 1 minute

### ISSUE THREAD

**Issue by mr-flame7892** [distubejs/ytdl-core#54]
## Describe the bug

When I'm trying to download a video that lasts more than a minute, the "readable" event isn't triggered and when I try to see if the stream is readable, it says that the stream is readable but no stream is returned (there's no error message). But when I tried to download videos that last less than a minute everything works correctly.

## Environment

- @distube/ytdl-core version: 4.13.7
- Node.js version: 20.15.1
- Operating system: Windows 11

**Comment by MR-Flame-exe** [comment]
It seems that some videos are playable even if its duration is over 1 minute, therefore the duration doesn't matter (for example: https://www.youtube.com/watch?v=jzi6RNVEOtA works perfectly for me). Also when the stream isn't readable, the "errored" property of the stream returns a 403 error message and the stream is destroyed:

![image_2024-08-01_202148128](https://github.com/user-attachments/assets/ceb49439-2378-4bf2-a950-d29d4c8ddefe)

**Comment by qubiack** [comment]
Are you using `agent` ?

**Comment by MR-Flame-exe** [comment]
> Are you using `agent` ?

Yes

**Comment by qubiack** [comment]
Can you provide 2 links: video is working and not working for you?

**Comment by MR-Flame-exe** [comment]
> Can you provide 2 links: video is working and not working for you?

Working link: https://www.youtube.com/watch?v=jzi6RNVEOtA

Not working link: https://www.youtube.com/watch?v=uu2XSQgdQDY

**Comment by qubiack** [comment]
@MR-Flame-exe both work for me in the latest version of ytdl. Could you provide a part of code you are using to download that files?

**Comment by MR-Flame-exe** [comment]
> @MR-Flame-exe both work for me in the latest version of ytdl. Could you provide a part of code you are using to download that files?

            var stream = ytdl(song.download_url, {
              highWaterMark: 1 << 25,
              filter: "audioonly",
              quality: "lowestaudio",
              agent,
            }).once("readable", async function () {

              console.log(`✅ - The stream of ${song.url} has been downloaded!`)

            })

**Comment by qubiack** [comment]
I think that I had that issue few years ago. Some YT files didn't have `audioonly` versions. You can check that by different API - `ytdl.getInfo(url, {agent})` . 

My workaround was to download always `mp4` and convert it into mp3 in next step.

**Comment by MR-Flame-exe** [comment]
> I think that I had that issue few years ago. Some YT files don't have `audioonly` versions. You can check that by different API - `ytdl.getInfo(url, {agent})` .
> 
> My workaround was to download always `mp4` and convert it into mp3 in next step.

Pretty sure it's not a problem related to the audioonly's filter, I mean every videos worked with the bot since today therefore I think it's not an issue related to my code, just an issue with the YouTube API or something. Btw I also tried to use ytdl-core instead of distube but it gets worse, no video was readable.

**Comment by skick1234** [comment]
On web client, which ytdl-core is using, have an A/B testing to prevent bots. I will investigate it and release an update after works.

**Comment by skick1234** [comment]
Also this issue related to #31

**Comment by jaysun0** [comment]
I had my app working from server in Finland. Most of the videos downloaded were just blank files. Sometitmes after 2,3 attemptes on each video - manaded to download normaly. Now switched app server location to another country. ~ Half an hour app is working fine. Not sure that it's 100% solution. Just for your information. Thank you all and me for concerns :)
