### ISSUE TITLE
Missing codecs and quality tags in live video getInfo

### ISSUE THREAD

**Issue by tux1765** [distubejs/ytdl-core#64]
## Describe the bug
When getting video info `ytdl.getInfo` on a live video the container, codec, videoCodec, and audioCodec are reuturning null. The qualityLabel is also missing as a whole on YouTube Live videos when isLive is true. This does not allow the `ytdl.chooseFormat` with `highest` or `lowest` as the quality option to choose the proper video quality.

## Environment

- @distube/ytdl-core version: 4.14.2
- Node.js version: 18.19.1
- Operating system: Ubuntu 22.04

**Comment by tux1765** [comment]
Just to expand on some findings. with `chooseFormats` and quality `highest` or `lowest` it seems that the highest quality returns the lowest video and vice versa. Willing to test and add more info if needed. Thank you!

**Comment by Guru322** [comment]
not just live video  , normal ytvideo too
many itags returning null codecs , not a single itag with both video and audio codec

## Environment

    @distube/ytdl-core version: 4.14.2
    Node.js version: 22.3.0
    Operating system: Arch

**Comment by robert-mefford** [comment]
Is there anyway to download video that has both video and audio?
I was using v4.13.5 and I can download video with both video/audio.
But with latest version I can not download both.

Is this expected result?

**Comment by skick1234** [comment]
This is expected since I moved to ios player, I'm finishing the android player to get more itag.

**Comment by robert-mefford** [comment]
Then should I download video and audio separately and merge them using ffmpeg package?

**Comment by skick1234** [comment]
Should be improved on `4.14.3`

**Comment by skick1234** [comment]
> Then should I download video and audio separately and merge them using ffmpeg package?

In the worse case, you have to do it for better output quality.

**Comment by tux1765** [comment]
@skick1234 Thank you for the quick work! Everything seems to be working again in latest release
