### ISSUE TITLE
"Sign in to confirm your age" issue even with cookies / userAgent

### ISSUE THREAD

**Issue by northamerican** [distubejs/ytdl-core#65]
## Describe the bug
In the past 48 hours or so, age-restricted videos return a "Sign in to confirm your age" error, even when supplying `ytdl.createAgent` with all .youtube.com cookies. 

## Environment
- @distube/ytdl-core version: 4.14.3
- Node.js version: 21.6.2
- Operating system: macOS

**Comment by Marbanz** [comment]
This will be hard to fix because now this uses ios and android players to retrieve the stream from the mobile api, so you need to find out how youtube manage cookies on mobile

**Comment by sepehrsamavati** [comment]
Version `4.13.7` was working for me. I received a deprecation warning and updated to `v4.14.3`, but it stopped working. After reverting back to `4.13.7`, it is now functioning correctly. Give it a try.

**Comment by northamerican** [comment]
@sepehrsamavati i can confirm this is a regression, likely in https://github.com/distubejs/ytdl-core/compare/4.13.7...4.14.0

**Comment by tux1765** [comment]
Can also confirm. I tried to export a cookie from a mobile browser as well and that does not seem to work either. When using my laptop though the cookie generated at least gets me from `Sign in to confirm your age` to `UnrecoverableError: This video may be inappropriate for some users.`

**Comment by northamerican** [comment]
@tux1765 

yup. with `4.13.7`, using these three youtube cookies : `__Secure-1PSID`, `__Secure-1PSIDTS`, `LOGIN_INFO`, each with the `name`, `value`, and `secure: true` was enough to download the video.
in `4.14`+, the error is now `This video may be inappropriate for some users.`

**Comment by skick1234** [comment]
I brought back web client parser for now, cookies should work as expected.
Anyway, 403 may happens with this method, I will investigate new way later (maybe tv client,...)

**Comment by skick1234** [comment]
I brought back the web client parser for now, so cookies should work as expected. However, a 403 error may occur with this method. I will investigate a new way later, perhaps using a TV client, instead.
