### ISSUE TITLE
YouTube Format Url shows up 403 error

### ISSUE THREAD

**Issue by TechBroCode** [distubejs/ytdl-core#66]
I installed this package from Node Js just few hours ago and when i made use of the ytdl.getInfo to get video formats. I got the video formats.... Fine, the problem here is that if i copy a format url value, take for instance url under itag 18 for 360p resolution video and paste it on my Google chrome or Microsoft Edge browser, it shows up a 403 error page instead (Forbidden) but if i paste the YouTube html url on some other video downloader site then i'll get the url to either stream or download the video. Now, both url from other video downloader site and my url gotten from @distube/ytdl-core looked alike. But their url plays the video while this one doesn't.

**Comment by skick1234** [comment]
It looks like are using an older version of ytdl-core, or the stream URL may be forbidden on different IPs. Please provide detailed steps to reproduce the error if you need further assistance.

**Comment by TechBroCode** [comment]
> It looks like are using an older version of ytdl-core, or the stream URL may be forbidden on different IPs. Please provide detailed steps to reproduce the error if you need further assistance.

I appended the installed library with @latest. Therefore, it's not an older version. Also, if it's IP issue, is there anyway i can clone my IP when initializing the library?
