### ISSUE TITLE
Can't use Brightdata proxy (error 407)

### ISSUE THREAD

**Issue by templth** [distubejs/ytdl-core#71]
## Describe the bug

I can't use Brightdata proxy. I got a 407 error.

I try this code:

```
const proxy = 'http://brd-customer-XXX:PWD@brd.superproxy.io:22225';
const proxyAuth = 'brd-customer-XXX:PWD';

const agent = ytdl.createProxyAgent({
  uri: proxy,
  token: `Basic ${proxyAuth}`
});

const audioStream = await ytdl(videoUrl, { agent, filter: 'audioonly', format: 'mp3' });
```

I also opened an issue on undici : https://github.com/nodejs/undici/issues/3442

## Debug File

N/A

## Environment

- @distube/ytdl-core version: 4.14.3
- Node.js version: 18
- Operating system: Linux Mint 21

**Comment by skick1234** [comment]
I cannot solve any problem with proxy, it should be due to your proxy error
