### ISSUE TITLE
I have IP restriction

### ISSUE THREAD

**Issue by yourshaxzod** [distubejs/ytdl-core#72]
I have thread limit, can you suggest me to not get thread limit.

It slows down significantly when I run through a proxy

I can't log in through cookies

--------------------

## Environment

- @distube/ytdl-core version: 4.14.3
- Node.js version: v20.15.1
- Operating system: Ubuntu 22.04

**Comment by ybd-project** [comment]
I also use a proxy, but the processing speed is now 5~8 seconds instead of the 1~2 seconds it used to be. So I am looking into the possibility of building my own fast proxy. (using Node.js)

**Comment by yourshaxzod** [comment]
> I also use a proxy, but the processing speed is now 5 ~ 8 seconds instead of the 1 ~ 2 seconds it used to be. So I am looking into the possibility of building my own fast proxy. (using Node.js)

I used cookie and it still works vps speed is better than proxy, for the cookie to work properly you must have two youtube accounts and after receiving the cookie of one you must switch to the next account and the account that received the cookie must be saved and do not log into the account that received the cookie again.

I don't know how long the cookie works, but I'd like to know

**Comment by ybd-project** [comment]
One question, what form of cookie are you using? I have been using EditThisCookie to get the following data.
```
{
    "domain": ".youtube.com",
    "expirationDate": 1234567890,
    "hostOnly": false,
    "httpOnly": true,
    "name": "---xxx---",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "value": "---xxx---"
}
```
Also, the environment that uses ytdl-core is a serverless function, but I have never had success using cookies before.

**Comment by yourshaxzod** [comment]
> One question, what form of cookie are you using? I have been using EditThisCookie to get the following data.
> 
> ```
> {
>     "domain": ".youtube.com",
>     "expirationDate": 1234567890,
>     "hostOnly": false,
>     "httpOnly": true,
>     "name": "---xxx---",
>     "path": "/",
>     "sameSite": "no_restriction",
>     "secure": true,
>     "session": false,
>     "value": "---xxx---"
> }
> ```
> 
> Also, the environment that uses ytdl-core is a serverless function, but I have never had success using cookies before.

cookies are only working on local computer, vps stopped working very fast and I'm using proxy again

**Comment by ybd-project** [comment]
> cookies are only working on local computer, vps stopped working very fast and I'm using proxy again

Some people in #76 have the same problem with cookies only working locally. I still think proxy is the way to go for now.

**Comment by gatecrasher777** [comment]
> I don't know how long the cookie works, but I'd like to know

YouTube uses cookie rotation while you have an active website page open. So cookies get updated every ten minutes. 
If it gets a chance to update, the previous cookies stop working.

**Comment by ybd-project** [comment]
> > I don't know how long the cookie works, but I'd like to know
> 
> YouTube uses cookie rotation while you have an active website page open. So cookies get updated every ten minutes. If it gets a chance to update, the previous cookies stop working.

That is terrible. But it seems a little strange that it works fine with proxies. (No cookies specified)

**Comment by hextor1** [comment]
> e. But

cookies not working on production server and also showing 403 error

**Comment by Riders004** [comment]
> I also use a proxy, but the processing speed is now 5 ~ 8 seconds instead of the 1 ~ 2 seconds it used to be. So I am looking into the possibility of building my own fast proxy. (using Node.js)

Can you share the code ?

**Comment by ybd-project** [comment]
> > I also use a proxy, but the processing speed is now 5 ~ 8 seconds instead of the 1 ~ 2 seconds it used to be. So I am looking into the possibility of building my own fast proxy. (using Node.js)
> 
> Can you share the code ?

I have not been able to build a proxy using Node.js because it was difficult.
However, I can give you a proxy IP that I used before.

**Comment by Riders004** [comment]
> > > I also use a proxy, but the processing speed is now 5 ~ 8 seconds instead of the 1 ~ 2 seconds it used to be. So I am looking into the possibility of building my own fast proxy. (using Node.js)
> > 
> > 
> > Can you share the code ?
> 
> I have not been able to build a proxy using Node.js because it was difficult. However, I can give you a proxy IP that I used before.

Bro I build using gpt but that valid proxy I'm getting is giving error connection issue for distube Ytdl
