### ISSUE TITLE
Throttling / Download url is inactive after 30 seconds.

### ISSUE THREAD

**Issue by jaysun0** [distubejs/ytdl-core#84]
## Describe the bug

I use distube/ytdl deployed on ubuntu server with agent(cookies) and all works fine and fast, but I can't download pretty large files, because right after 30 seconds smth happens and stream just stops. Anything what can be downloaded before 30 seconds (even large 40 minutes or more videos, ~600mb in weight) - is being downloaded fast. After 30 secs - download progress is just 0 mbs, it stucks.
Any thoughts on how to get around this? Or at least direction to go?)
## Environment

- @distube/ytdl-core version: latest 4.14.4
- Node.js version: lts
- Operating system: ubuntu 24

**Comment by gathilas** [comment]
I’m getting the same thing.

**Comment by phucngo2** [comment]
I'm encountering the same issue. After 30 seconds, the download progress randomly gets stuck at points that are multiples of 10mb (e.g., 240mb, 250mb).

**Comment by Ali-Nazim** [comment]
Same issue here, after a minute or so of streaming, it randomly stops.
I'm on @distube/ytdl-core version: latest 4.14.4

**Comment by gathilas** [comment]
It seems like it stops because of a 403 error part way through the download.

**Comment by jaysun0** [comment]
> It seems like it stops because of a 403 error part way through the download.

Why do you think so?

**Comment by jaysun0** [comment]
> > > It seems like it stops because of a 403 error part way through the download.
> > 
> > 
> > Why do you think so?
> 
> I saw someone else mention that they were getting a 403 mid stream so I added some code to my implementation and found I was also getting a 403 error when the stream stops downloading.

Thank you for info. 

So, in theory, not as implementation - but to my understanding:  changing cookies on the run and making a new request will give again some download time?

**Comment by jaysun0** [comment]
And one more question. 

Look - I download video, pretty fast, everything is ok. After 30 seconds it starts throttling. 
I immediately rerun function, requesting the same video with the same cookies - and it starts download again very fast.

Why it works fast again with same ip and cookies?

**Comment by gathilas** [comment]
I have no idea how to fix the problem, just stating what I found. I'm still getting the error. Hopefully someone smarter than I can figure it out.

**Comment by jaysun0** [comment]
More info about issue:

When I use range as option when downloading big-weight video (for example: options.range = { start: 1000gb } ), download is throttling immediately. It is not stopping but speed less than 2mbs while ussally more than 50 or even 100. 
Also if in the same video I set range { start: 500gb } - it will download fast till 1000  and then start throttling. Numbers are not exact, just for example.

So, it kind of allows to download fast till some point and then throttles.

**Comment by plasma119** [comment]
I got the same problem: 403 after 30 seconds for like 80+ videos

After some digging around on internet I saw a mention of "using the option IOS fixed the problem" (forgot where I saw it)

Manually selecting other format did work, so I assume the problem is related to some specific video formats.
I extracted the format details and found that there is 2 format with same itag but different url, one has "c=ANDROID" and the other has "c=IOS"

I added filter to ytdl.chooseFormat to filter out format.url containing "c=ANDROID" and it seems to be working fine again now

**Comment by jaysun0** [comment]
> I got the same problem: 403 after 30 seconds for like 80+ videos
> 
> After some digging around on internet I saw a mention of "using the option IOS fixed the problem" (forgot where I saw it)
> 
> Manually selecting other format did work, so I assume the problem is related to some specific video formats. I extracted the format details and found that there is 2 format with same itag but different url, one has "c=ANDROID" and the other has "c=IOS"
> 
> I added filter to ytdl.chooseFormat to filter out format.url containing "c=ANDROID" and it seems to be working fine again now

Thanks for info. Also using ios formats now. Works good, but sometimes I get 401 (I always use cookies). 401 also kind of strange because you can get 401, then try to download the same video again and it works.

**Comment by UtterDonkey** [comment]
I have the same issue, filtering out format.url containing "c=ANDROID" doesn't work for me. Stream cuts off at exactly 30 seconds for me.
