### ISSUE TITLE
Error: Sign in to confirm you're not a robot

### ISSUE THREAD

**Issue by MyDapitt** [distubejs/ytdl-core#88]
## Describe the bug
In version 4.14.3, there was an error: sign in to confirm you're not a robot. This case same in version 4.14.4

## Debug File
![Screenshot_20240813_203711_Chrome Dev](https://github.com/user-attachments/assets/0a07bb1d-1220-493c-ab92-c931a6c84ac7)

## Environment

- @distube/ytdl-core version: 4.14.3, 4.14.4
- Node.js version: 20.16.0
- Operating system: Linux

**Comment by tonykx** [comment]
#76

**Comment by Talhary** [comment]
using cookie editor get the cookies as NetScape. 
```const cookiesString =  `name=value;name=value;`
const cookies = CookiesString.split(';').map(cookie => {
  const [name, ...value] = cookie.split('=');
  return {
    name: name.trim(),
    value: value.join('=').trim(),
  };
});

// console.log(cookies);

const agentOptions = {
  pipelining: 5,
  maxRedirections: 10,
 
};

// agent should be created once if you don't want to change your cookie
const agent = ytdl.createAgent(cookies, agentOptions);
``` 
how use the agent with your request like this . 
```
const res = await ytdl.getInfo(url,{agent});
``` 
This should solve Sign in problem

**Comment by ybd-project** [comment]
[@ybd-project/ytdl-core](https://github.com/ybd-project/ytdl-core)
I have now released ytdl-core with the ability to specify poToken and visitorData.
The iOS and Android players are experiencing bot errors, but we have been able to work around this by using the Web Creator player.
These issues are being improved, so please wait. We are looking forward to receiving reports of issues.

**Comment by tonykx** [comment]
> [@ybd-project/ytdl-core](https://github.com/ybd-project/ytdl-core) Agora lancei ytdl-core com a capacidade de especificar poToken e visitorData. Os players de iOS e Android estão enfrentando erros de bot, mas conseguimos contornar isso usando o player Web Creator. Esses problemas estão sendo aprimorados, portanto, aguarde. Estamos ansiosos para receber relatórios de problemas.

Envie aqui a função adaptada pra uso

**Comment by dylaniscool54** [comment]
https://api.proxyscrape.com/v4/free-proxy-list/get?request=display_proxies&protocol=http&proxy_format=protocolipport&format=json&timeout=20000

you gotta test them all on loop and store in an array
and when a download is required use one

alot of these proxies dont even work
