### ISSUE TITLE
when I try to use proxy agent in requestOptions, undici crashes with InvalidArgumentError 

### ISSUE THREAD

**Issue by Danko14** [distubejs/ytdl-core#9]
Thanks for the fork and for help!

Here is the error:
` InvalidArgumentError: unsupported opts.agent. Did you mean opts.client?
25|test  |     at Object.request (/home/ubuntu/ponyapp_debug/node_modules/undici/index.js:84:13)
25|test  |     at exports.request (/home/ubuntu/ponyapp_debug/node_modules/@distube/ytdl-core/lib/utils.js:178:28)
25|test  |     at /home/ubuntu/ponyapp_debug/node_modules/@distube/ytdl-core/lib/info.js:127:59
25|test  |     at Cache.getOrSet (/home/ubuntu/ponyapp_debug/node_modules/@distube/ytdl-core/lib/cache.js:29:19)
25|test  |     at getWatchHTMLPageBody (/home/ubuntu/ponyapp_debug/node_modules/@distube/ytdl-core/lib/info.js:127:33)
25|test  |     at getWatchHTMLPage (/home/ubuntu/ponyapp_debug/node_modules/@distube/ytdl-core/lib/info.js:262:20)
25|test  |     at retryFunc (/home/ubuntu/ponyapp_debug/node_modules/@distube/ytdl-core/lib/info.js:218:22)
25|test  |     at async pipeline (/home/ubuntu/ponyapp_debug/node_modules/@distube/ytdl-core/lib/info.js:159:23)
25|test  |     at async exports.getBasicInfo (/home/ubuntu/ponyapp_debug/node_modules/@distube/ytdl-core/lib/info.js:66:14) {
25|test  |   code: 'UND_ERR_INVALID_ARG'
25|test  | }
`

and here is my function call: 
` getOxylabsDataCenterProxyAgent() {
    const proxy = `http://user:password@dc.pr.oxylabs.io:10000`;
    const agent = new HttpsProxyAgent.HttpsProxyAgent(proxy);
    return agent 
  }
  
info = await ytdl.getBasicInfo(videoUrl, {
        requestOptions: {
          agent: this.getOxylabsDataCenterProxyAgent(),
        },
   });
`

here is undici source code: 
`  const { agent, dispatcher = getGlobalDispatcher() } = opts

    if (agent) {
      throw new InvalidArgumentError('unsupported opts.agent. Did you mean opts.client?')
    }
`

the error didnt appear in native ytdl lib though

**Comment by skick1234** [comment]
Since we use undici, we need to use a different way to apply proxy.

Documentation: https://github.com/nodejs/undici/blob/main/docs/api/ProxyAgent.md#new-proxyagentoptions

Example:
```js
const { ProxyAgent } = require('undici');

const proxyAgent = new ProxyAgent('my.proxy.server')
// or
const proxyAgent = new ProxyAgent({ uri: 'my.proxy.server' })

const ytdl = require('@distube/ytdl-core')
ytdl.getBasicInfo("url", {
    requestOptions: {
        dispatcher: proxyAgent
    },
})
```
I will provide this in README.md later.

**Comment by skick1234** [comment]
The above way is not supported anymore, use the new guide in the readme page instead.

https://github.com/distubejs/ytdl-core#proxy-support
