### ISSUE TITLE
unable to get video info , UnrecoverableError: Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by MohamedAdany** [distubejs/ytdl-core#90]
## Describe the bug
Error getting info for videoId: BR8MUdch1eA UnrecoverableError: Sign in to confirm you’re not a bot
    at exports.playError (/var/task/node_modules/@distube/ytdl-core/lib/utils.js:164:12)
    at exports.getBasicInfo (/var/task/node_modules/@distube/ytdl-core/lib/info.js:46:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

## Debug File
try {
              
             const  info = await ytdl.getInfo(videoId, { lang: clientLang });
               } catch (error) {
              console.error("Error getting info for videoId:", videoId, error);
## Environment

- @distube/ytdl-core version:^4.14.4
- Node.js version:18
- Operating system:windows

**Comment by miketuannguyen** [comment]
Try using cookie https://github.com/distubejs/ytdl-core?tab=readme-ov-file#cookies-support. In my case, it works.

**Comment by MohamedAdany** [comment]
it worked for a single day, what to do when the cookie expires? i cant change it everyday, need a stable solution

**Comment by omenocal** [comment]
I tried using a proxy. Bought 3 proxy IPs, and after 3 days, they were all blocked too.

**Comment by Jk950305** [comment]
having the same issue. Is it because Youtube blocks certain ip or something?

**Comment by yourshaxzod** [comment]
> Try using cookie https://github.com/distubejs/ytdl-core?tab=readme-ov-file#cookies-support. In my case, it works.

How often are cookies updated?

**Comment by aaf-30** [comment]
It happens because YouTube restricts your IP address, just use a proxy or VPN and you won't get a 403 error even without logging in.

**Comment by ybd-project** [comment]
[@ybd-project/ytdl-core](https://github.com/ybd-project/ytdl-core)
I have now released ytdl-core with the ability to specify poToken and visitorData.
The iOS and Android players are experiencing bot errors, but we have been able to work around this by using the Web Creator player.
These issues are being improved, so please wait. We are looking forward to receiving reports of issues.
