### ISSUE TITLE
Request Error With Status 403

### ISSUE THREAD

**Issue by Talhary** [distubejs/ytdl-core#92]
## Describe the bug
I got the Urls of Videos But the urls doesn't work they return 403. I checked in browser , with axios and fetch. All return same error.

## Debug File
```
export const downloadVideo = async (url, quality) => {
const res = await ytdl.getInfo(url,{agent});
const title = res['player_response']['videoDetails']['title']
const formate = res['player_response']['streamingData']['formats']
// console.log(formate)
const adaptiveFormate = res['player_response']['streamingData']['adaptiveFormats'].map(format=>{
  return {itag: format.itag,mimeType:format.mimeType, url: format.url, quality: format.qualityLabel, width: format.width, height: format.height}
})
const data = adaptiveFormate.filter(f=>{
  if(!quality ) return f;
  return f.height >= quality 
})
if(!data.length)
return {title: title, urls: formate[0] };

return {title: title,urls:data[data.length-1] };
}
```
## Environment

- @distube/ytdl-core version:
- Node.js version:v20.16.0
- Operating system: window 10

**Comment by miketuannguyen** [comment]
Try using cookie https://github.com/distubejs/ytdl-core?tab=readme-ov-file#cookies-support. In my case, it works.

**Comment by Talhary** [comment]
> Try using cookie https://github.com/distubejs/ytdl-core?tab=readme-ov-file#cookies-support. In my case, it works.

Already using cookies.

**Comment by luthfipun** [comment]
try update decipher https://github.com/distubejs/ytdl-core/issues/91#issuecomment-2290360827

**Comment by xaksis** [comment]
> Try using cookie https://github.com/distubejs/ytdl-core?tab=readme-ov-file#cookies-support. In my case, it works.

@miketuannguyen Could you tell me, what version of ytdl-core are you using?

**Comment by Talhary** [comment]
> > Try using cookie https://github.com/distubejs/ytdl-core?tab=readme-ov-file#cookies-support. In my case, it works.
> 
> @miketuannguyen Could you tell me, what version of ytdl-core are you using?

Latest I installed it yesterday

**Comment by xaksis** [comment]
I'm experiencing the same issue as you, @Talhary. My question was for @miketuannguyen to see if he's on a different version that is working.

**Comment by Talhary** [comment]
> I'm experiencing the same issue as you, @Talhary. My question was for @miketuannguyen to see if he's on a different version that is working.

oh. I didn't see that name.

**Comment by miketuannguyen** [comment]
> I'm experiencing the same issue as you, @Talhary. My question was for @miketuannguyen to see if he's on a different version that is working.

I'm using the latest version of @distubejs/ytdl-core. Please read carefully the instruction and follow it. The first time I tried using cookie, it doesn't work. But, in the second time, I follow the instruction more carefully and it works like a charm.
I also didn't remove localhost part or any part from the cookie i got.

**Comment by robertlockesoftware** [comment]
What didn't you do the first time? I followed the instructions and am getting a 403

**Comment by xaksis** [comment]
@Talhary where is your code hosted? I have my stuff on gcp and I think youtube is now blocking data warehouse IPs which is why this doesn't seem to work anymore. Not sure what the fix could be other than using a proxy that works.

**Comment by EmilianoTalamo** [comment]
I'm using both proxy and cookies. It works fine locally but once deployed to AWS it gets blocked.
