### ISSUE TITLE
Getting error 403 when downloading official music

### ISSUE THREAD

**Issue by tb-sumberjaya** [distubejs/ytdl-core#93]
I have used cookies and proxy, to download other videos goes smoothly. However, I got a 403 error when downloading an official music video (a video uploaded by a channel whose name ends in -topic).
Here's an example of a video that got the 403 error

https://youtu.be/9vDIzVuDzTs

Btw, I have tried downloading that video using yt-dlp CLI and it worked, I think it should be possible to use this library too.

## Environment

- @distube/ytdl-core version: latest
- Node.js version: 22.5.1
- Operating system: Debian

**Comment by xaksis** [comment]
I'm also seeing the same for all videos. Tried refreshing cookies. Didn't help.

**Comment by tb-sumberjaya** [comment]
This issue was resolved on my end, I used another proxy and cookies. Now it's working normally for any videos.
