### ISSUE TITLE
get cookies correctly，but still throw an error

### ISSUE THREAD

**Issue by td236** [distubejs/ytdl-core#96]
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: connect ENETUNREACH 31.13.94.37:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
Emitted 'error' event on PassThrough instance at:
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4062,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '31.13.94.37',
  port: 443
}

Node.js v20.16.0

**Comment by ybd-project** [comment]
[@ybd-project/ytdl-core](https://github.com/ybd-project/ytdl-core)
I have now released ytdl-core with the ability to specify poToken and visitorData.
The iOS and Android players are experiencing bot errors, but we have been able to work around this by using the Web Creator player.
These issues are being improved, so please wait. We are looking forward to receiving reports of issues.
